Screen:
	name: "splash"
	MDFloatLayout:
		md_bg_color: rgba(230, 230, 255, 255)
		MDIcon:
			icon: "instagram"
			font_size: "100sp"
			pos_hint: {"center_x":.5, "center_y":.6}
			color: rgba(107, 127, 214, 255)
			halign: "center"

		MDLabel:
			text: "Instagurame"
			pos_hint: {"center_x":.5, "center_y":.45}
			halign: "center"
			font_name: "Roboto"
			color: rgba(107, 127, 214, 255)
			bold: True
			font_size: "28sp"