

Screen:
	name: "login"
	MDFloatLayout:
		md_bg_color: rgba(58, 58, 58, 255)

    MDLabel:
		text : 'Hi User !'
		font_size : 'sp'
		pos_hint: {"center_x":.55, "center_y":.9}
		color: rgba(255,255,255, 255)

    MDLabel:
		text : 'Forgot your password? '
		font_size : '30sp'
		pos_hint: {"center_x":.55, "center_y":.83}
		color: rgba(255,255,255, 255)

    MDLabel:
		text : 'Find it Here ! '
		font_size : '30sp'
		pos_hint: {"center_x":.55, "center_y":.777}
		color: rgba(255,255,255, 255)