#:import get_color_from_hex kivy.utils.get_color_from_hex


Screen:
	name: "settings"
	MDFloatLayout:
		md_bg_color: rgba(21, 34, 56,255)
        canvas:
            Color:
                rgb: 1, 1, 1
            Ellipse:
                pos: 100, 450
                size: 150 , 150
                source: 'asset/logotoko.png'
                angle_start: 0
                angle_end: 360
        
        MDLabel:
            text



        